name: travel_news_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts: 
    - family: GellixSemiBold
      fonts:
        - asset: assets/fonts/Gellix-SemiBold.ttf
    - family: GellixBold
      fonts:
        - asset: assets/fonts/Gellix-Bold.ttf
    - family: GellixLight
      fonts:
        - asset: assets/fonts/Gellix-Light.ttf
    - family: GellixMedium
      fonts:
        - asset: assets/fonts/Gellix-Medium.ttf
    